export const DEFAULT_LAYOUT_OPTIONS = {
  personWidth: 16,
  personHeight: 16,
  personPaddingX: 16,
  personLineHeight: 16,
  personPaddingY: 16,
  personNameFontSize: 16,
  personNoteFontSize: 12,
  personNameFontWeight: "400",
  personNoteFontWeight: "400",
  personFontFamily: "IBM Plex Sans, Segoe UI, sans-serif",
  personGap: 32,
  generationGap: 64,
  unionSize: 16,
  unionOffsetY: 0,
  paddingX: 24,
  paddingY: 24,
  iterations: 8,
  childGroupThreshold: 5,
  childGroupMaxColumns: 3,
  childGroupRowGap: 20,
};
